// ===================================
// Main.cpp file generated by OptFrame
// Project $name
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

// LOADER IS NOT DEFAULT ANYMORE. USE ONLY IF YOU NEED...
//#include "../OptFrame/Loader.hpp"

#include "$project.h"

using namespace std;
using namespace optframe;
using namespace $project;

int main(int argc, char **argv)
{
   RandGen rg;
   
   // Initialize here all your OptFrame components 
   // (ProblemInstance, Evaluator, Constructive, ...)

   cout << "Program ended successfully" << endl;
   
   return 0;
}
