// ===================================
// Main.cpp file generated by OptFrame
// Project $name
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

#include "../OptFrame/Loader.hpp"
#include "$project.h"

using namespace std;
using namespace optframe;
using namespace $project;

int main(int argc, char **argv)
{
   RandGen rg;
   
   Loader<Rep$project, MY_ADS $commadproject> optframe(rg);
   
   $projectProblemCommand pc(rg);

   cout << "Program ended successfully" << endl;
   
   return 0;
}
