# Makefile generated by OptFrame MCT (shell version)
all: examples
	g++ ./MyProjects/main$project.cpp ./OptFrame/Scanner++/Scanner.cpp -o MyProjects/main$project

examples: tsp eternityii pmedcap

tsp:
	g++ -Wall ./Examples/mainTSP.cpp ./OptFrame/Scanner++/Scanner.cpp -o Examples/TSPExample

eternityii:
	g++ -Wall ./Examples/mainEternityII.cpp ./OptFrame/Scanner++/Scanner.cpp -o Examples/EternityIIExample

pmedcap:
	g++ -Wall ./Examples/mainPMedCap.cpp ./OptFrame/Scanner++/Scanner.cpp -o Examples/PMedCapExample
	
clean: 
	rm -f Examples/TSPExample
	rm -f Examples/EternityIIExample
	rm -f Examples/PMedCapIIExample
	rm -f MyProjects/main$project