# Makefile generated by OptFrame MCT (shell version)
all: user$project

user$project:
	g++ main$project.cpp $project/ProblemInstance.cpp $project/Evaluator.cpp $project/Constructive$constructive.cpp  $project/NSSeq$neighborhood.cpp $project/ProblemCommand.cpp ../OptFrame/Scanner++/Scanner.cpp -o main$project

examples: tsp eternityii pmedcap

tsp:
	g++ -Wall ../Examples/mainTSP.cpp ../OptFrame/Scanner++/Scanner.cpp -o ../Examples/TSPExample

eternityii:
	g++ -Wall ../Examples/mainEternityII.cpp ../OptFrame/Scanner++/Scanner.cpp -o ../Examples/EternityIIExample

pmedcap:
	g++ -Wall ../Examples/mainPMedCap.cpp ../OptFrame/Scanner++/Scanner.cpp -o ../Examples/PMedCapExample
	
clean: 
	rm -f ../Examples/TSPExample
	rm -f ../Examples/EternityIIExample
	rm -f ../Examples/PMedCapIIExample
	rm -f main$project
