# Makefile generated by OptFrame MCT (shell version)
all: examples
	g++ ./MyProjects/main$project.cpp ./OptFrame/Scanner++/Scanner.cpp -o main$project

examples: tsp eternityii pmedcap

tsp:
	g++ -Wall ./Examples/mainTSP.cpp ./OptFrame/Scanner++/Scanner.cpp -o TSPExample

eternityii:
	g++ -Wall ./Examples/mainEternityII.cpp ./OptFrame/Scanner++/Scanner.cpp -o EternityIIExample

pmedcap:
	g++ -Wall ./Examples/mainPMedCap.cpp ./OptFrame/Scanner++/Scanner.cpp -o PMedCapExample
	
clean: 
	rm -f TSPExample
	rm -f EternityIIExample
	rm -f PMedCapIIExample
	rm -f main$project