// ======================================
// RepTest.cpp file generated by OptFrame
// ======================================

/* OptFrame default includes */
#include <stdlib.h>
#include <math.h>
#include <iostream>
#include <vector>
#include "./OptFrame/Util/Matrix.hpp"

/* User defined includes */
$include

using namespace std;

int main(int argc, char **argv)
{
    $rep* x;
    x=x;
    return 0;
}
