//Rename to mainTSP.cpp to run the example

// ===================================
// Main.cpp file generated by OptFrame
// Project Traveling Salesman Problem
// ===================================

#include <stdlib.h>
#include <math.h>

#include <iostream>

using namespace std;

#include <set>

#include "../OptFrame/OptFrame.hpp"
#include "../OptFrame/Examples/TSP.h"

int main(int argc, char **argv)
{
	srand(time(NULL));

	// Optimal value for berlin52 is 7542

	Scanner scanner(new File("../OptFrame/Examples/TSP/tsplib/berlin52.txt"));

	TSPProblemInstance* p = new TSPProblemInstance(scanner);

	RandomInitialSolutionTSP is(p);

	SolutionTSP& s = is.generateSolution();

	NSEnumSwap ns(p);

	s.print();

	TSPEvaluator eval(p);
	EvaluationTSP* e;

	e = &eval.evaluate(s);

	e->print();
	cout << endl;

	HeuristicFactory<RepTSP, MemTSP> factory;
	factory.add_initsol(&is);
	factory.add_ev(&eval);
	factory.add_ns(&ns);


	OptFrame<RepTSP, MemTSP> optframe(&factory);
	//optframe.execute();

	string cmd("read ");
	if (argc > 1) cmd += argv[1]; else cmd += "example.opt";
	optframe.execute(string("read ") + argv[1]);

	cout << "Program ended successfully" << endl;

	return 0;
}
