all: mitsp

mitsp:
	#g++ -I../../include --std=c++17 -fconcepts src/mainMImpTSP.cpp -o build/app_MiTSP 2> error-gcc.err 
	g++ -I../../include --std=c++17 -fconcepts src/mainMImpTSP.cpp -o build/app_MiTSP

