// ===================================
// Main.cpp file generated by OptFrame
// Project Particao
// ===================================

#include <math.h>
#include <stdlib.h>

#include <iostream>

/*
#include "../OptFrame/Interactive.hpp"
#include "PN.h"

using namespace std;
using namespace optframe;
using namespace PN;

int
main(int argc, char** argv)
{
   Interactive<RepPN, MY_ADS> optf;
   //optframe.loadCallCommand();

   optf.loadCommand(new PNProblemCommand);

   optf.execute("system.read ./execPN.opt");

   optf.execute();

   cout << "Program ended successfully" << endl;

   return 0;
}
*/

#include <PN/PN.h>

using namespace std;
using namespace optframe;
using namespace PN;

int main(int argc, char** argv) {
  PNProblemCommand p;

  cout << "Program ended successfully" << endl;

  return 0;
}
