// ===================================
// Main.cpp file generated by OptFrame
// Project Simple Cycle Problem
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

#include "../Examples/SCP.h"
#include "../OptFrame/Loader.hpp"

using namespace std;
using namespace optframe;
using namespace SCP;

int main(int argc, char **argv)
{
   RandGen rg;
   
   Loader<RepSCP, MY_ADS > optframe(rg);
   
   SCPProblemCommand pc(rg);

   cout << "Program ended successfully" << endl;
   
   return 0;
}
