examples: tsp eternityII pmedcap

tsp:
	g++ -Wall mainTSP.cpp ../OptFrame/Scanner++/Scanner.cpp -o TSPExample

eternityII:
	g++ -Wall mainEternityII.cpp ../OptFrame/Scanner++/Scanner.cpp -o EternityIIExample

pmedcap:
	g++ -Wall mainPMedCap.cpp ../OptFrame/Scanner++/Scanner.cpp -o PMedCapExample
	
clean: 
	rm -f TSPExample
	rm -f EternityIIExample
	rm -f PMedCapIIExample
