// OptFrame 4.2 - Optimization Framework
// Copyright (C) 2009-2021 - MIT LICENSE
// https://github.com/optframe/optframe
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// ===================================
// Main.cpp file generated by OptFrame
// Project PMedCap
// ===================================

#include <iostream>
#include <math.h>
#include <stdlib.h>

#include "PMedCap.h"
#include <OptFrame/Loader.hpp>
#include <OptFrame/Move.hpp> // for testing
#include <OptFrame/Timer.hpp>

using namespace std;
using namespace optframe;
using namespace pmedcap;

int
main(int argc, char** argv)
{
   Timer walltimer;

   srand(time(NULL));
   RandGen rg(time(NULL));

   Scanner scanner(File("./Examples/PMedCap/InstancesLorena/SJC1"));

   //double tempo = 120;

   PCAPProblemInstance p(scanner);
   PCAPEvaluator e(p);
   GeneralEvaluator<ESolutionPCAP>& e2 = e;
   PCAPInitialSolutionGreedy is_greedy(p, e2, rg);
   //SolutionPCAP s = *is_greedy.generateSolution(100); // timelimit 100
   ESolutionPCAP se = *is_greedy.initialSearch(StopCriteria<EvaluationPCAP>(100)).first; // timelimit 100

   XSolution AUTO_CONCEPTS& s = se.first;
   ////XEvaluation& e = se.second;

   NSSeqSWAP nsSwap(p, rg);

   s.print();

   e.evaluate(s).print();

   PCAPSolCheck(p, s);

   Loader<RepPCAP, OPTFRAME_DEFAULT_ADS, SolutionPCAP, EvaluationPCAP, ESolutionPCAP> optframe(rg);
   optframe.factory.addComponent(is_greedy);
   optframe.factory.addComponent(e);
   optframe.factory.addComponent(nsSwap);

   // do something!

   cout << "Program ended successfully" << endl;

   return 0;
}
