// ===================================
// Main.cpp file generated by OptFrame
// Project Particao
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

#include "../OptFrame/Interactive.hpp"
#include "PN.h"

using namespace std;
using namespace optframe;
using namespace PN;

int main(int argc, char **argv)
{
   Interactive<RepPN, MY_ADS > optframe;
   //optframe.loadCallCommand();

   optframe.loadCommand(new PNProblemCommand);

   optframe.execute("system.read ./execPN.opt");

   optframe.execute();

   cout << "Program ended successfully" << endl;
   
   return 0;
}
