# User makefile generated by OptFrame MCT (Make a Compilable Thing!)

all: mctAppHFM

CC=g++

mctAppHFM:      mainHFM.o       HFMScanner.o  
	g++ $(GCC_FLAGS) mainHFM.o    HFMScanner.o  -o app_HFM

mainHFM.o: mainHFM.cpp  HFM/Representation.h  HFM/Solution.h 
	g++ -c $(GCC_FLAGS) -fopenmp mainHFM.cpp -o mainHFM.o
	
HFMScanner.o: ../OptFrame/Scanner++/Scanner.cpp
	g++ -c $(GCC_FLAGS) ../OptFrame/Scanner++/Scanner.cpp -o HFMScanner.o

#HFMprintable.o: ../OptFrame/Util/printable.cpp
#	g++ -c $(GCC_FLAGS) ../OptFrame/Util/printable.cpp -o HFMprintable.o


GCC_FLAGS= -g -Wall -O3 --std=c++17 -fconcepts #-fno-exceptions -fno-rtti #TODO: disable exceptions

#.PHONY: all #clean
	
clean: 
	rm -f app_HFM
	rm -f HFM*.o
