// ===================================
// Main.cpp file generated by OptFrame
// Project Traveling Salesman Problem
// ===================================

#include <stdlib.h>
#include <math.h>

#include <iostream>

using namespace std;

#include <set>

#include "../OptFrame.hpp"
#include "TSP.h"

int main(int argc, char **argv)
{
	srand(time(NULL));
	RandGen rg(time(NULL));

	// Optimal value for berlin52 is 7542

	Scanner scanner(new File("./OptFrame/Examples/TSP/tsplib/berlin52.txt"));

	TSPProblemInstance* p = new TSPProblemInstance(scanner);

	RandomInitialSolutionTSP is(p,rg);

	SolutionTSP& s = is.generateSolution();

	NSEnumSwap ns(p,rg);

	s.print();

	TSPEvaluator eval(p);
	EvaluationTSP* e;

	e = &eval.evaluate(s);

	e->print();
	cout << endl;

	HeuristicFactory<RepTSP, MemTSP> factory(rg);
	factory.add_initsol(&is);
	factory.add_ev(&eval);
	factory.add_ns(&ns);


	OptFrame<RepTSP, MemTSP> optframe(factory);
	optframe.execute();

	cout << "Program ended successfully" << endl;

	return 0;
}
