name: Binary Builder
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.7'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: binarybuilder
      - name: Run `build_tarballs.jl`
        run: |
          julia -e 'import Pkg; Pkg.add("BinaryBuilder")'
          julia --project=binarybuilder support/binarybuilder/build_tarballs.jl
