name: Example HFMVRP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/HFMVRP/
      run: |
        mkdir -p build/
        make

