name: Example MODM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Examples-LTS-MODM:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/MODM/
      run: make
    - name: bazel
      working-directory: ./Examples/LTS/MODM/
      run: bazel build ...
    - name: cmake
      working-directory: ./Examples/LTS/MODM/
      run: pip install cmake --break-system-packages && rm -rf build && mkdir -p build && cd build && cmake .. -GNinja && ninja


