name: Example HFMVRP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Examples-LTS-HFMVRP:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/HFMVRP/
      run: |
        mkdir -p build/
        make
    - name: cmake
      working-directory: ./Examples/LTS/HFMVRP/
      run: pip install cmake --break-system-packages && rm -rf build && mkdir -p build && cd build && cmake .. -GNinja && ninja


