name: Example Eternity II

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/EternityII/
      run: make
    - name: bazel
      working-directory: ./Examples/LTS/EternityII/
      run: bazel build ...
    - name: cmake
      working-directory: ./Examples/LTS/EternityII/
      run: cxxbuild

