name: Example PN

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Examples-LTS-PN:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/  PN/
      run: make

