name: Example MITSP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Examples-LTS-MITSP:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Examples/LTS/MITSP/
      run: make
    - name: bazel
      working-directory: ./Examples/LTS/MITSP/
      run: bazel build ...
