// ===================================
// Main.cpp file generated by OptFrame
// Project EFP
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>
#include <numeric>
#include "../../../OptFrame/RandGen.hpp"
#include "../../../OptFrame/Util/RandGenMersenneTwister.hpp"

using namespace std;
using namespace optframe;
using namespace EFP;

int microGridLiuAppliedEnergy(int argc, char **argv)
{
	cout << "Welcome to Micro Grid Liu Applied Energy Dataset Calibration Mode..." << endl;
	RandGenMersenneTwister rg;
	//long  1412730737
	long seed = time(NULL); //CalibrationMode
	seed = 9;
	cout << "Seed = " << seed << endl;
	srand(seed);
	rg.setSeed(seed);

	if (argc != 8)
	{
		cout << "Parametros incorretos!" << endl;
		cout << "Os parametros esperados sao: nome nomeValidationSet saida parameters options precision" << endl;
		exit(1);
	}

	const char* caminho = argv[1];
	const char* caminhoValidation = argv[2];
	const char* caminhoOutput = argv[3];
	const char* caminhoParameters = argv[4];
	int instN = atoi(argv[5]);
	int stepsAhead = atoi(argv[6]);
	int mu = atoi(argv[7]);

	string nome = caminho;
	string nomeValidationSet = caminhoValidation;
	string nomeOutput = caminhoOutput;
	string parametersFile = caminhoParameters;

	//===================================
	cout << "Parametros:" << endl;
	cout << "nome=" << nome << endl;
	cout << "nomeValidationSet=" << nomeValidationSet << endl;
	cout << "nomeOutput=" << nomeOutput << endl;
	cout << "nomeParameters=" << parametersFile << endl;
	cout << "instN=" << instN << endl;
	cout << "stepsAhead=" << stepsAhead << endl;
	cout << "mu=" << mu << endl;
	//===================================

	//CONFIG FILES FOR CONSTRUTIVE 0 AND 1
	vector<string> vParametersFiles;
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_124Points");
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_7Points");
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_2Points");
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_BasedOnAutoCor");
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_BasedOnAutoCor2");
	vParametersFiles.push_back("./MyProjects/ConfigParameters/MG/1Column_Liu");

	vector<string> explanatoryVariables;

	//DATA FROM LIU
	string fileMicroGridA = "./MyProjects/EFP/Instance/microGridLiuAE/A";
	string fileMicroGridB = "./MyProjects/EFP/Instance/microGridLiuAE/B";
	string fileMicroGridC = "./MyProjects/EFP/Instance/microGridLiuAE/C";
	string fileMicroGridD = "./MyProjects/EFP/Instance/microGridLiuAE/D";

	//TREATED DATA FROM LIU
	string fileMicroGridAT = "./MyProjects/EFP/Instance/microGridLiuAETreated/A";
	string fileMicroGridBT = "./MyProjects/EFP/Instance/microGridLiuAETreated/B";
	string fileMicroGridCT = "./MyProjects/EFP/Instance/microGridLiuAETreated/C";
	string fileMicroGridDT = "./MyProjects/EFP/Instance/microGridLiuAETreated/D";
	vector<string> vInstances;
	vInstances.push_back(fileMicroGridAT);
	vInstances.push_back(fileMicroGridBT);
	vInstances.push_back(fileMicroGridCT);
	vInstances.push_back(fileMicroGridDT);
	int rInstance = rg.rand(4);

	explanatoryVariables.push_back(vInstances[0]);

	//small trainning used to be good, like 2, 3
	// WRONG, 10 seams to be the BEST

	treatForecasts rF(explanatoryVariables);

	//vector<vector<double> > batchOfBlindResults; //vector with the blind results of each batch

	/*int beginValidationSet = 0;
	 int nTrainningRoundsValidation = 50;
	 int nValidationSamples = problemParam.getNotUsedForTest() + nTrainningRoundsValidation * stepsAhead;
	 cout << "nValidationSamples = " << nValidationSamples << endl;
	 int nTotalForecastingsValidationSet = nValidationSamples;

	 vector<vector<double> > validationSet; //validation set for calibration
	 validationSet.push_back(rF.getPartsForecastsEndToBegin(0, beginValidationSet, nTotalForecastingsValidationSet));
	 validationSet.push_back(rF.getPartsForecastsEndToBegin(1, beginValidationSet, nTotalForecastingsValidationSet + stepsAhead));
	 validationSet.push_back(rF.getPartsForecastsEndToBegin(2, beginValidationSet, nTotalForecastingsValidationSet + stepsAhead));
	 */

	int maxMu = 100;
	int maxInitialDesv = 10;
	int maxMutationDesv = 30;
	int maxPrecision = 300;

	int nBatches = 1;
	int timeES = 180;
	int timeVND = 0;
	int timeILS = 0;
	int timeGRASP = 0;

	vector<vector<double> > vfoIndicatorCalibration; //vector with the FO of each batch

	vector<SolutionEFP> vSolutionsBatches; //vector with the solution of each batch

	for (int n = 0; n < nBatches; n++)
	{
		int randomPrecision = rg.rand(maxPrecision) + 10;
		int randomParametersFiles = rg.rand(vParametersFiles.size());
		int evalFOMinimizer = rg.rand(NMETRICS); //tree is the number of possible objetive function index minimizers
		int evalAprox = rg.rand(2); //Enayatifar aproximation using previous values
		int construtive = rg.rand(3);
		double initialDesv = rg.rand(maxInitialDesv) + 1;
		double mutationDesv = rg.rand(maxMutationDesv) + 1;
		mu = rg.rand(maxMu) + 1;
		int lambda = mu * 6;
		double alphaACF = rg.rand01(); //limit ACF for construtive ACF
		int alphaSign = rg.rand(2);
		if (alphaSign == 0)
			alphaACF = alphaACF * -1;

		// ============ FORCES ======================
		randomParametersFiles = 2; // best file
		//randomParametersFiles = 5; // liu config file
		mu = 10;
		lambda = mu * 6;
		initialDesv = 10;
		mutationDesv = 20;
		randomPrecision = 50;		//10
		//randomParametersFiles = 0;
		evalFOMinimizer = MAPE_INDEX;
		evalAprox = 2;
		alphaACF = -1;
		construtive = 2;
		// ============ END FORCES ======================

		// ============= METHOD PARAMETERS=================
		methodParameters methodParam;
		//seting up ES params
		methodParam.setESMU(mu);
		methodParam.setESLambda(lambda);
		methodParam.setESInitialDesv(initialDesv);
		methodParam.setESMutationDesv(mutationDesv);
		methodParam.setESMaxG(100000);
		//seting up Construtive params
		methodParam.setConstrutiveMethod(construtive);
		methodParam.setConstrutivePrecision(randomPrecision);
		vector<double> vAlphaACFlimits;
		vAlphaACFlimits.push_back(alphaACF);
		methodParam.setConstrutiveLimitAlphaACF(vAlphaACFlimits);
		//seting up Eval params
		methodParam.setEvalAprox(evalAprox);
		methodParam.setEvalFOMinimizer(evalFOMinimizer);
		// ==========================================

		// ================== READ FILE ============== CONSTRUTIVE 0 AND 1
		ProblemParameters problemParam;
		//ProblemParameters problemParam(vParametersFiles[randomParametersFiles]);
		int nVR = 168;
		int nSA = 1;
		problemParam.setStepsAhead(nSA);
		stepsAhead = problemParam.getStepsAhead();
		// =========================================== CONSTRUTIVE 0 AND 1
		//========ADAPTATION FOR CONSTRUTIVE 2 ===============
		if (construtive == 2) //ACF construtive
			problemParam.setMaxLag(400);
		int maxLag = problemParam.getMaxLag();
		//=================================================

		int maxTrainningRounds = 20;
		int nTrainningRounds = rg.rand(maxTrainningRounds) + 1;
		nTrainningRounds = 672;
		int nTotalForecastingsTrainningSet = maxLag + nTrainningRounds * stepsAhead;

		int beginTrainingSet = 672;

		cout << "BeginTrainninningSet: " << beginTrainingSet;
		cout << "\t #SamplesTrainningSet: " << nTotalForecastingsTrainningSet << endl;
		cout << "maxNotUsed: " << problemParam.getMaxLag() << endl;
		cout << "#StepsAhead: " << stepsAhead << endl << endl;

		//else
		//beginTrainingSet = nTotalForecastingsValidationSet + n * (nTotalForecastingsTrainningSet / 10);

		/*
		 while (beginTrainingSet + nTotalForecastingsTrainningSet > rF.getForecastsDataSize())
		 {
		 beginTrainingSet = 744;
		 nTrainningRounds = rg.rand(maxTrainningRounds) + 1;
		 nTotalForecastingsTrainningSet = maxNotUsedForTest + nTrainningRounds * stepsAhead;
		 }*/

		vector<vector<double> > trainningSet; // trainningSetVector
		trainningSet.push_back(rF.getPartsForecastsEndToBegin(0, beginTrainingSet, nTotalForecastingsTrainningSet));

		ForecastClass forecastObject(trainningSet, problemParam, rg, methodParam);

		pair<Solution<RepEFP>&, Evaluation&>* sol;

		int optMethod = rg.rand(2);
		optMethod = 1;
		if (optMethod == 1)
			sol = forecastObject.run(timeES, timeVND, timeILS);
		else
			sol = forecastObject.runEFP(timeGRASP, timeILS); // GRASP + ILS

		vector<double> foIndicatorCalibration;

		int nValidationSamples = sol->first.getR().earliestInput + nVR * stepsAhead;
//		vector<vector<double> > validationSet; //validation set for calibration
//		validationSet.push_back(rF.getPartsForecastsEndToBegin(0, beginTrainingSet + stepsAhead, nValidationSamples));
//		vector<double> foIndicatorsWeeks;
//		foIndicatorsWeeks = forecastObject.returnErrors(sol, validationSet);
//		foIndicatorCalibration.push_back(foIndicatorsWeeks[MAPE_INDEX]);
//		foIndicatorCalibration.push_back(foIndicatorsWeeks[RMSE_INDEX]);

		cout << "nValidationSamples:" << nValidationSamples << endl;
		//int beginValidationSet = 0;
		for (int w = 3; w >= 0; w--)
		{
			vector<vector<double> > validationSet; //validation set for calibration
			validationSet.push_back(rF.getPartsForecastsEndToBegin(0, w * 168, nValidationSamples));
			vector<double> foIndicatorsWeeks;
			foIndicatorsWeeks = forecastObject.returnErrors(sol, validationSet);
			foIndicatorCalibration.push_back(foIndicatorsWeeks[MAPE_INDEX]);
			//foIndicatorCalibration.push_back(foIndicatorsWeeks[RMSE_INDEX]);
		}

		double intervalOfBeginTrainningSet = double(beginTrainingSet) / double(rF.getForecastsDataSize());

		foIndicatorCalibration.push_back(randomPrecision);
		foIndicatorCalibration.push_back(randomParametersFiles);
		foIndicatorCalibration.push_back(nTrainningRounds);
		foIndicatorCalibration.push_back(beginTrainingSet);
		foIndicatorCalibration.push_back(intervalOfBeginTrainningSet);
		foIndicatorCalibration.push_back(nTotalForecastingsTrainningSet);
		foIndicatorCalibration.push_back(mu);
		foIndicatorCalibration.push_back(lambda);
		foIndicatorCalibration.push_back(initialDesv);
		foIndicatorCalibration.push_back(mutationDesv);
		foIndicatorCalibration.push_back(timeES);
		foIndicatorCalibration.push_back(timeVND);
		foIndicatorCalibration.push_back(timeILS);
		foIndicatorCalibration.push_back(timeGRASP);
		foIndicatorCalibration.push_back(evalFOMinimizer);
		foIndicatorCalibration.push_back(evalAprox);
		foIndicatorCalibration.push_back(construtive);
		foIndicatorCalibration.push_back(alphaACF);
		foIndicatorCalibration.push_back(optMethod);
		foIndicatorCalibration.push_back(rInstance);
		foIndicatorCalibration.push_back(seed);
		//getchar();
		//cout << foIndicatorCalibration << endl;
		vfoIndicatorCalibration.push_back(foIndicatorCalibration);
		vSolutionsBatches.push_back(sol->first);

	}

	// =================== PRINTING RESULTS ========================
	for (int n = 0; n < nBatches; n++)
	{

		for (int i = 0; i < vfoIndicatorCalibration[n].size(); i++)
			cout << vfoIndicatorCalibration[n][i] << "\t";

		cout << endl;
	}
	// =======================================================

	// =================== PRINTING RESULTS ON FILE ========================
	string calibrationFile = "./microGridCalibration";

	FILE* fResults = fopen(calibrationFile.c_str(), "a");
	for (int n = 0; n < nBatches; n++)
	{
		for (int i = 0; i < vfoIndicatorCalibration[n].size(); i++)
			fprintf(fResults, "%.7f\t", vfoIndicatorCalibration[n][i]);
		fprintf(fResults, "\n");
	}

	fclose(fResults);
	// =======================================================

	return 0;
}

//
//for (int w = 4; w >= 1; w--)
//	{
//		vector<double> foIndicatorsMAPE;
//		vector<double> foIndicatorsRMSE;
//
//		for (int day = 1; day <= 7; day++)
//		{
//			vector<vector<double> > validationSet; //validation set for calibration
//			validationSet.push_back(rF.getPartsForecastsEndToBegin(0, w * 168 - stepsAhead * day, nValidationSamples));
//			vector<double> foIndicators;
//			foIndicators = forecastObject.returnErrors(sol, validationSet);
//			foIndicatorsMAPE.push_back(foIndicators[MAPE_INDEX]);
//			foIndicatorsRMSE.push_back(foIndicators[RMSE_INDEX]);
//		}
//		double sumMAPE = accumulate(foIndicatorsMAPE.begin(), foIndicatorsMAPE.end(), 0.0);
//		double sumRMSE = accumulate(foIndicatorsRMSE.begin(), foIndicatorsRMSE.end(), 0.0);
//
//		foIndicatorCalibration.push_back(sumMAPE/foIndicatorsMAPE.size());
//		foIndicatorCalibration.push_back(sumRMSE/foIndicatorsRMSE.size());
//	}
